### ISSUE TITLE
Redundant information

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/eYY-4yp-project-template#1]
Hi @NuwanJ, Why don't we take this info (team members' Github, Linkedin profiles) from the API? https://github.com/cepdnaclk/eYY-4yp-project-template/commit/27a8ff6a16f2f05b86c93ddf92fb6fd37005fe51

**Comment by NuwanJ** [comment]
Yes, no more need, other two templates already updates. Forgot about this.

**Comment by NuwanJ** [comment]
It seems to be already removed 3 days ago. @gihanjayatilaka do you still see the parameters?
